config/routes.rb
Vswiki::Application.routes.draw do

  root 'pages#index'

  resources :pages, path: "/"

end

app/models/page.rb
require "#{Rails.root}/lib/vswiki/parser"

class Page < ActiveRecord::Base

  validates :title, presence: { message: "Cannot save with empty title" }
  validates :wikititle, uniqueness: { message:
    "page with that title already exists" }

  before_validation :build_wikititle

  def self.page_exists?(wikititle)
    Page.exists?(wikititle: wikititle)
  end

  def self.make_wikititle(str)
    Vswiki::Parser.new.make_wikititle(str)
  end

  def build_wikititle
    if self.title
      self.wikititle = Page.make_wikititle(self.title)
    end
  end

  def formatted_html
     Vswiki::Parser.new.to_html(self.wikitext) if self.wikitext
  end

  def to_param
    wikititle
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :get_page, only: [:show, :edit, :update, :destroy]
  before_filter :get_sidebar, only: [:show, :index]

  def index

    if params[:go_to_page]
      redirect_to action: "show", id: to_wikititle(params[:go_to_page])
    end
  end

  def new
    title = params[:title] || ""
    @page = Page.new(title: title)
  end

  def create
    @prev_page = Page.find_by(wikititle: to_wikititle(params[:page][:title]))
    @page = Page.create(page_params)
    if @page.valid?
      redirect_to_show_or_keep_editing
    else
      render :new
    end
  end

  def show
    return redirect_to new_page_path(title: params[:id]) unless @page

    if @page.redirect_to.present?
      redirect_to(page_path(to_wikititle(@page.redirect_to)),
                  flash: {info: redirect_message})
    end
  end

  def edit
  end

  def update
    if @page.update_attributes(page_params)
      redirect_to_show_or_keep_editing
    else
      # should not happen normally, as title not editable via form and
      # there are currently no validations on other attributes
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to root_url
  end


  private

  def get_page
    @page = Page.find_by(wikititle: params[:id])
  end

  def get_sidebar
    @pages = Page.all

  end

  def page_params
    params.require(:page).permit(:title, :wikitext, :redirect_to)
  end

  def redirect_to_show_or_keep_editing
    if params[:save_and_edit]
      render "edit"
    else
      redirect_to @page
    end
  end

  def to_wikititle(text)
    Page.make_wikititle(text)
  end

  def redirect_message
    view_context.raw("Redirected from #{view_context.link_to @page.title, edit_page_path(@page)}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def make_error_display_string(err)
    msg = err.join
    if msg =~ /already exists/
      msg << "; "
      msg << link_to("edit the existing page", edit_page_path(@prev_page))
      msg << " or enter a different title"
    end
    msg
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-dismissible alert-<%= key %>">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_delete_confirm.html.erb
<div class="modal" id="delete-confirm" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Confirm page deletion</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to remove the page <em><%= @page.title%></em>?</p>
      </div>
      <div class="modal-footer">
        <%= button_tag "Cancel", type: "button", class: "btn btn-default", data: { dismiss: "modal" } %>
        <%= link_to "Yes, delete!", @page, method: :delete, class: "btn btn-danger btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_edit_controls.html.erb
<%= button_tag type: "submit", name: "commit", class: "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-save text-primary"></span> Save
<% end %>
<%= button_tag type: "submit", name: "save_and_edit", class: "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-save text-primary"></span>
  <span class="glyphicon glyphicon-edit text-primary"></span>
  Save &amp; edit
<% end %>
<%= link_to @page, class: "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-remove text-warning"></span> Cancel
<% end %>

app/views/pages/_page_errors.html.erb
<% if page.errors.any? %>
  <div class="alert alert-danger">
    There 
    <% if page.errors.count == 1 %>
      was a problem:
    <% else %>
      were <%= pluralize(page.errors.count, "problem") %>:
    <% end %>
    <ul>
      <% page.errors.messages.each do |attribute, error| %>
	<li><%= raw(make_error_display_string(error)) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/pages/_show_controls.html.erb
<%= link_to edit_page_path(@page), class: "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-edit text-primary"></span> Edit
<% end %>
<%= button_tag type: "button", class: "btn btn-default btn-sm",
    data: { toggle: "modal", target: "#delete-confirm" } do %>
  <span class="glyphicon glyphicon-remove text-danger"></span> Delete
<% end %>

app/views/pages/_sidebar.html.erb
<div class="hidden-xs col-sm-2 sidebar">
  <aside>
    <div class="homelink" %>
      <%= link_to "Home", pages_path %>
    </div>


    <div class="goto-page" %>
      <%= form_tag("/", method: "get") do %>
        <div class="input-group">
          <%= text_field_tag(:go_to_page, nil, placeholder: "Go to page", class: "form-control input-sm") %>
          <span class="input-group-btn">
            <%= button_tag(type: "submit", title: "Go", class: "btn btn-default btn-sm") do%>
              <span class="glyphicon glyphicon-chevron-right text-primary"></span>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
    <br>
    <div>
      <%= link_to new_page_path, class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-plus text-success"></span> Create a new page
      <% end %>
    </div>

    <h1>SideBar</h1>
    <% @pages.each do |page|%>
    <div>
        <p><%= link_to "#{page.title}", page_path(page)%></p>
    </div>
    <%end%>


  </aside>
</div>

app/views/pages/edit.html.erb
<% provide(:title, "Editing #{@page.title}") %>

<div class="row">
  <div class="col-xs 12 col-sm-12 col-md-12 col-lg12">
    <h1>Editing "<%= @page.title %>"</h1>

    <%= form_for @page do |f| %>

      <%= f.label :title, "Page title" %>
      <%= f.text_field :title, required: true, class: "tinymce",:rows => 40, :cols => 120 %>

      <div class="form-group wikitext-edit">
        <%= f.label :wikitext, "Page contents", class: "sr-only" %>
        <%= f.text_area :wikitext, class: "tinymce", :rows => 40, :cols => 120%>
      </div>

        <%= render "edit_controls" %>
    <% end %>
  </div>
</div>
<%= tinymce %>

app/views/pages/index.html.erb
<% provide(:title, "BuKa Wiki") %>

<div class="row">
  <%= render "sidebar" %>

  <div class="col-xs-10 col-sm-10 col-md-10 col-lg10">

    <h1>BuKaWiki Home Page</h1>

    <h1>The Unofficial Official Wiki for BuKas<h1>

    <h4>Created by <%= link_to "Gustavo Guimarães (BuKa 2014-2015)", "https://www.humboldt-life.de/profile/u4141783419"%>.</h4> <h4>Updated and made relevant by you, amazing BuKa fellows of the present and future</h4>

    <footer>
    <strong>"THE BEER-WARE LICENSE"</strong>
    <p>* Gustavo coded this for you. As long as you retain this notice you can do whatever you want with this stuff. If we meet some day, and you think this stuff is cool or better worth it , you can buy him a beer in return :-)</p>
    </footer>

  <%= link_to new_page_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-plus text-success"></span> Create a new page
  <% end %>

  </div>
</div>

app/views/pages/new.html.erb
<% provide(:title, "New page") %>

<div class="row">
  <div class="col-xs 12 col-sm-12 col-md-12 col-lg12">
    <h1>New page</h1>

    <%= form_for @page do |f| %>
      <div class="form-group">
        <%= render "page_errors", page: f.object, prev_page: @prev_page %>

        <%= f.label :title, "Page title" %>
        <%= f.text_field :title, required: true, class: "tinymce" %>
      </div>

      <div class="form-group wikitext-edit">
        <%= f.label :wikitext, "Page contents", class: "sr-only" %>

        <%= f.text_area :wikitext, class: "tinymce", :rows => 40, :cols => 120 %>
      </div>

      <%= render "edit_controls" %>
    <% end %>
  </div>
</div>
<%= tinymce %>

app/views/pages/show.html.erb
<% provide(:title, @page.title) %>

<div class="row">

  <%= render "sidebar" %>

  <div class="col-xs-12 col-sm-10 page-content">
    <h1><%= @page.title %></h1>

    <div id="top-controls">
      <%= render "show_controls" %>
    </div>

    <div class="formatted-page-content">
      <%= @page.wikitext.html_safe %>
    </div>

    <div id="bottom-controls">
      <%= render "show_controls" %>
    </div>

    <div id="timestamps">
      <em>Created: <%= @page.created_at %> <br />
        Last updated: <%= @page.updated_at %></em>
    </div>

    <%= render "delete_confirm" %>
  </div>
</div>